# This will require each of these plugins automatically.
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin

name: Yousra Aafer
author: Yousra Aafer
